### ISSUE TITLE
 Bad state: Too many elements

### ISSUE THREAD

**Issue by Flutter-Stack** [cetorres/multiselect_formfield#7]
I have trying out example from here https://pub.dev/packages/multiselect_formfield .

instead of 7 datasource items I gave 14 items.  I am getting below error.

            ⣷I/flutter (31891): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31891): The following StateError was thrown building MultiSelectFormField(dirty, dependencies:
       ⣾I/flutter (31891): [_InheritedTheme, _LocalizationsScope-[GlobalKey#b6ebe], _FormScope], state:
I/flutter (31891): FormFieldState<dynamic>#fdbcc):
I/flutter (31891): Bad state: Too many elements
I/flutter (31891): 
I/flutter (31891): The relevant error-causing widget was:
I/flutter (31891):   MultiSelectFormField
I/flutter (31891):   /lib/ui/screens/addProduct.dart:394:24
I/flutter (31891): 
I/flutter (31891): When the exception was thrown, this was the stack:
I/flutter (31891): #0      ListMixin.singleWhere (dart:collection/list.dart:174:11)
I/flutter (31891): #1      new MultiSelectFormField.<anonymous closure>._buildSelectedOptions.<anonymous closure> (package:multiselect_formfield/multiselect_formfield.dart:54:49)
I/flutter (31891): #2      List.forEach (dart:core-patch/growable_array.dart:285:8)
I/flutter (31891): #3      new MultiSelectFormField.<anonymous closure>._buildSelectedOptions (package:multiselect_formfield/multiselect_formfield.dart:53:24)
I/flutter (31891): #4      new MultiSelectFormField.<anonymous closure> (package:multiselect_formfield/multiselect_formfield.dart:136:60)
I/flutter (31891): #5      FormFieldState.build (package:flutter/src/widgets/form.dart)
I/flutter (31891): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (31891): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (31891): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #9      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #17     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (31891): #18     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (31891): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #46     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #58     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #66     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #70     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #74     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #92     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #96     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #100    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #104    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #106    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (31891): #107    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (31891): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #111    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #115    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #125    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #127    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #131    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #135    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
        
Reloaded 3 of 758 libraries in 934ms.
I/flutter (31891): #139    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #143    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #147    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #151    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #153    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #157    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #159    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #165    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #167    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #169    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #173    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #176    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #177    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #181    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #183    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #184    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #186    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #187    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #188    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter (31891): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #190    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #194    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (31891): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #198    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (31891): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #200    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (31891): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #204    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (31891): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (31891): #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (31891): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (31891): #208    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (31891): #209    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (31891): #210    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (31891): #211    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (31891): #212    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (31891): #213    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
I/flutter (31891): #215    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (31891): #216    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (31891): #217    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (31891): (elided one frame from package dart:async-patch)
I/flutter (31891): 
I/flutter (31891): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31891): Another exception was thrown: RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (31891): Another exception was thrown: _RenderInkFeatures object was given an infinite size during layout.
I/flutter (31891): Another exception was thrown: RenderPhysicalModel object was given an infinite size during layout.
I/flutter (31891): Another exception was thrown: RenderPadding object was given an infinite size during layout.
I/flutter (31891): Another exception was thrown: RenderFlex object was given an infinite size during layout.

**Comment by cetorres** [comment]
Hi @Flutter-Stack. Unfortunately I couldn't reproduce the error. I added 15 items to the example's datasource and it's working normally. Could you try again with the newer stable version of Flutter? Or let me know your environment configuration and steps to reproduce the error. Thanks.
